#pragma once
#include "render/c_renderer.h"
#include "ecs/components/c_cameracomponent.h"
#include "input/input.h"
#include "filesystem/filesystem.h"
#include "asset/asset.h"
#include "screen/screen.h"
#include "c_world.h"
#include "c_engine.h"