#pragma once
#include <Windows.h>
#include <GL/glew.h>
#include <GL/wglew.h>
#include <GL/GL.h>
#include <fstream>
#include <string>
#include <vector>
#include <thread>
#include <mutex>
#include <cstdio>
#include <cmath>
#include <iostream>
#include "log.h"
#include "nlohmann/json.hpp"
#include "transform.h"
#include <glm.hpp>
#include <D3D11.h>
#include "D3DX11.h"
#include "c_job.h"